name: miigaik
description: "MIIGAiK mobile application"
publish_to: 'none'

version: 0.2.0+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  bloc_event_transformers: ^2.0.0
  equatable: ^2.0.7
  
  dio: ^5.9.0
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1

  package_info_plus: ^9.0.0
  easy_localization: ^3.0.8
  get_it: ^8.2.0
  flutter_screenutil: ^5.9.3
  shimmer_animation: ^2.1.0
  flutter_dotenv: ^6.0.0
  flutter_widget_from_html: ^0.17.0
  url_launcher: ^6.3.2
  photo_view: ^0.15.0
  datetime_loop: ^1.5.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  
  talker_flutter: ^5.0.1
  talker_dio_logger: ^5.0.1
  talker_bloc_logger: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  icon_font_generator: ^4.0.0

  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - config/.env
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: Icons
      fonts:
        - asset: assets/icons/icons.otf
