name: miigaik
description: "MIIGAiK mobile application"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0

  dio: ^5.9.0
  package_info_plus: ^9.0.0
  hive: ^2.2.3
  easy_localization: ^3.0.8
  get_it: ^8.2.0

  talker_flutter: ^5.0.1
  talker_dio_logger: ^5.0.1
  talker_bloc_logger: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  icon_font_generator: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: Icons
      fonts:
        - asset: assets/icons/icons.otf
